[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
trezo_hook = "8h1qfZ42zcZpTTmYLLG8TrcPurgnGHCD2NHn3nRcZyXH"
trezo_core = "Fg6PaFpoGXkYsidMpWxTWqkZxJotP7R9R3jJfG8h6Y2G"

[programs.localnet]
trezo_hook = "8h1qfZ42zcZpTTmYLLG8TrcPurgnGHCD2NHn3nRcZyXH"
trezo_core = "Fg6PaFpoGXkYsidMpWxTWqkZxJotP7R9R3jJfG8h6Y2G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p trezo-core"
