import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./provider";
import NextTopLoader from 'nextjs-toploader'
import AppWalletProvider from "../components/walletAdapter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark" suppressHydrationWarning>
      {/* <Providers> */}
        {/* <AppWalletProvider> */}
          <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen transition-colors duration-300`}>
            {/* <NextTopLoader color="#333" /> */}
            {children}
          </body>
        {/* </AppWalletProvider> */}
      {/* </Providers> */}
    </html>
  );
}
